sudo: required
services:
  - docker
script:
  - ./run build
  - ./run dist
deploy:
  fqdn: carriedonbothsides.com
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: master
